name: Phrase License Check
description: Check the licenses of your dependencies with lawa
inputs:
  # ruby-version:
  #   description: 'The Ruby version to use'
  #   required: false
  #   default: '3.1.3'
  # ruby-bundler-version:
  #   description: 'The Ruby bundler version to use'
  #   required: false
  #   default: '2.1.4'
  working-directory:
    description: 'The working directory to run lawa in'
    required: false
    default: .
  decisions-file:
    description: 'The path to the license decisions file'
    required: false
    default: .license-decisions.yml
  github-token:
    description: 'The GitHub token to read phrase/lawa repository'
    required: true
  # package-managers:
  #   description: 'The package managers to check licenses for'
  #   required: true

runs:
  using: "composite"
  steps:
    # - name: Set up Ruby
    #   uses: ruby/setup-ruby@0cde4689ba33c09f1b890c1725572ad96751a3fc # pin@v1.178.0
    #   with:
    #     ruby-version: ${{ inputs.ruby-version }}
    # - name: Install compatible bundler version
    #   shell: bash
    #   run: gem install bundler:${{ inputs.ruby-bundler-version }}
    # - name: Install lawa
    #   shell: bash
    #   run: |
    #     bundle config unset deployment
    #   env:
    #     BUNDLE_GITHUB__COM: x-access-token:${{ inputs.github-token }}
    - name: Run lawa
      shell: bash
      run: |
        cd ${{ inputs.working-directory }}
        bundle config set frozen false
        bundle add -g development lawa --github "phrase/lawa" --ref "3fae651668059c520c24b79fbca852da46c98b27"
        bundle exec lawa --enabled-package-managers bundler --decisions-file=${{ inputs.decisions-file }}
      env:
        BUNDLE_GITHUB__COM: x-access-token:${{ inputs.github-token }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
