name: Phrase Golang License Check
on:
  workflow_call:
    inputs:
      go-version:
        required: false
        type: string
        default: 1.19
      ruby-version:
        required: false
        type: string
        default: 3.1.3
      ruby-bundler-version:
        required: false
        type: string
        default: 2.1.4
      working-directory:
        required: false
        type: string
        default: .
      decisions-file:
        required: false
        type: string
        default: .license-decisions.yml
    secrets:
      github-token:
        required: true

jobs:
  lawa:
    name: lawa
    runs-on: ubuntu-latest
    steps:
      - name: Checkout app
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ inputs.go-version }}
      - name: Set up Ruby
        uses: ruby/setup-ruby@0cde4689ba33c09f1b890c1725572ad96751a3fc # pin@v1.178.0
        with:
          ruby-version: ${{ inputs.ruby-version }}
      - name: Install compatible bundler version
        run: gem install bundler:${{ inputs.ruby-bundler-version }}
      - name: Install lawa
        run: |
          cd ${{ inputs.working-directory }}
          touch Gemfile.lawa
          echo "source 'https://rubygems.org'" >> Gemfile.lawa
          echo -e "gem 'lawa', github: 'phrase/lawa'" >> Gemfile.lawa
          bundle _${{ inputs.ruby-bundler-version }}_ config unset deployment
          BUNDLE_GEMFILE=Gemfile.lawa bundle _${{ inputs.ruby-bundler-version }}_ install
        env:
          BUNDLE_GITHUB__COM: x-access-token:${{ secrets.github-token }} }}
      - name: Run lawa
        run: BUNDLE_GEMFILE=Gemfile.lawa bundle _${{ inputs.ruby-bundler-version }}_ exec lawa --enabled-package-managers=gomodules --decisions-file=${{ inputs.decisions-file }}
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
